In [6]:
import importlib, utils
importlib.reload(utils)
utils.build_merged.clear()
print("[hot reload] utils reloaded and build_merged cache cleared")

2026-03-24 16:25:00.679 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.679 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.680 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.681 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.682 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.682 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.683 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.683 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.684 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:25:00.684 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

[hot reload] utils reloaded and build_merged cache cleared

# Inspect DB merge flow for overview table

The following python cell prints the exact code for build_merged and _compute_delegate_summary, then runs checks for delegate 13613.

In [7]:
import inspect
import pandas as pd
from utils import build_merged, _compute_delegate_summary, load_data, source_mtimes, load_remappings

print("=== build_merged code ===")
print(inspect.getsource(build_merged))
print("=== _compute_delegate_summary code ===")
print(inspect.getsource(_compute_delegate_summary))

df_p, df_i, df_abbrd = load_data(source_mtimes())
print("persons shape:", df_p.shape, "occurrences shape:", df_i.shape)
print("13613 in persons count:", (df_p["delegate_id"].astype(str) == "13613").sum())
print("duplicate delegate_ids in persons:", df_p["delegate_id"].astype(str).duplicated().sum())

remappings = load_remappings()
df_merged, n_placeholder, n_remapped, summary = build_merged(df_p, df_i, df_abbrd, extra_delegates=None, remappings=remappings, name_col="fullname")
print("build_merged result:", df_merged.shape, "placeholders", n_placeholder, "remapped", n_remapped)
print("summary shape:", summary.shape)
print("13613 in summary:", summary[summary["delegate_id"] == "13613"].shape)
print("duplicate delegate_id in summary:", summary["delegate_id"].duplicated().sum())

summary2 = _compute_delegate_summary(df_merged, df_p, "fullname")
print("recomputed summary shape:", summary2.shape)
print("13613 in recomputed summary:", summary2[summary2["delegate_id"] == "13613"].shape)
print("duplicate delegate_id recomputed:", summary2["delegate_id"].duplicated().sum())

2026-03-24 16:25:14.983 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

=== build_merged code ===
@st.cache_data(show_spinner="Merging data…", hash_funcs=_HASH_FUNCS, persist="disk")
def build_merged(
    df_p: pd.DataFrame,
    df_i: pd.DataFrame,
    df_bio: pd.DataFrame | None,
    extra_delegates: list[dict] | None = None,
    remappings: list[dict] | None = None,
    name_col: str = "fullname",
) -> tuple[pd.DataFrame, int, int, pd.DataFrame]:
    """Merge occurrences + persons, apply remappings, filter placeholders.

    Returns ``(merged_df, n_placeholder_rows, n_remapped_rows, summary_df)``.
    The summary (one row per delegate) is computed here so it shares this
    function's cache entry — no second hashing of the large merged DataFrame.
    """
    _n_placeholder_rows: int = 0
    _n_remapped_rows: int = 0

    persons = df_p.copy()
    if "delegate_id" in persons.columns:
        persons["delegate_id"] = persons["delegate_id"].astype(str)
    if "delegate_id" in df_i.columns:
        df_i = df_i.copy()
        df_i["delegate_id"] = df_i["delegate_id"].astype(str)
    if df_bio is not None:
        df_bio = df_bio.copy()
        if "delegate_id" not in df_bio.columns and "id_persoon" in df_bio.columns:
            df_bio = df_bio.rename(columns={"id_persoon": "delegate_id"})
        if "delegate_id" in df_bio.columns:
            df_bio["delegate_id"] = df_bio["delegate_id"].astype(str)

    # append manually-added delegates (republic_add_*)
    if extra_delegates:
        extra_df = pd.DataFrame(extra_delegates)
        for col in persons.columns:
            if col not in extra_df.columns:
                extra_df[col] = pd.NA
        extra_sub = extra_df[persons.columns]
        # Avoid FutureWarning from concatenating columns that are all-NA.
        keep_cols = [c for c in extra_sub.columns if c == "delegate_id" or not extra_sub[c].isna().all()]
        if "delegate_id" not in keep_cols and "delegate_id" in extra_sub.columns:
            keep_cols.insert(0, "delegate_id")
        persons = pd.concat([persons, extra_sub[keep_cols]], ignore_index=True)

    # attach birth/death year
    if "birth_year" not in persons.columns and df_bio is not None:
        for by in ("birth_year", "geboortejaar", "geboorte", "born", "birth"):
            if by in df_bio.columns and "delegate_id" in df_bio.columns:
                persons = persons.merge(
                    df_bio[["delegate_id", by]]
                    .rename(columns={by: "birth_year"})
                    .drop_duplicates(subset=["delegate_id"]),
                    on="delegate_id", how="left")
                break
        for dy in ("death_year", "sterfjaar", "overlijden", "died", "death"):
            if dy in df_bio.columns and "delegate_id" in df_bio.columns:
                persons = persons.merge(
                    df_bio[["delegate_id", dy]]
                    .rename(columns={dy: "death_year"})
                    .drop_duplicates(subset=["delegate_id"]),
                    on="delegate_id", how="left")
                break
        if "birth_year" not in persons.columns:
            for lj in ("leefjaren", "levensjaren", "leven"):
                if lj in df_bio.columns and "delegate_id" in df_bio.columns:
                    tmp = df_bio[["delegate_id", lj]].drop_duplicates(subset=["delegate_id"]).copy()
                    tmp["birth_year"], tmp["death_year"] = _parse_leefjaren(tmp[lj].astype(str))
                    persons = persons.merge(
                        tmp[["delegate_id", "birth_year", "death_year"]],
                        on="delegate_id", how="left")
                    break

    # hlife fallback
    if df_bio is not None and "hlife" in df_bio.columns and "delegate_id" in df_bio.columns:
        extra_bio_cols = ["hlife"]
        for c in ("min_year", "max_year"):
            if c in df_bio.columns:
                extra_bio_cols.append(c)
        hl = (
            df_bio[["delegate_id"] + extra_bio_cols]
            .drop_duplicates(subset=["delegate_id"])
            .copy()
        )
        for c in extra_bio_cols:
            hl[c] = pd.to_numeric(hl[c], errors="coerce")
        persons = persons.merge(hl, on="delegate_id", how="left")
        if "birth_year" not in persons.columns:
            persons["birth_year"] = pd.NA
        if "death_year" not in persons.columns:
            persons["death_year"] = pd.NA
        mask_no_birth = persons["birth_year"].isna() & persons["hlife"].notna()
        mask_no_death = persons["death_year"].isna() & persons["hlife"].notna()
        persons.loc[mask_no_birth, "birth_year"] = (
            persons.loc[mask_no_birth, "hlife"] - 40).astype("Int64")
        persons.loc[mask_no_death, "death_year"] = (
            persons.loc[mask_no_death, "hlife"] + 30).astype("Int64")
    elif df_bio is not None and "delegate_id" in df_bio.columns:
        active_cols = [c for c in ("min_year", "max_year") if c in df_bio.columns]
        if active_cols:
            act_df = (
                df_bio[["delegate_id"] + active_cols]
                .drop_duplicates(subset=["delegate_id"])
                .copy()
            )
            for c in active_cols:
                act_df[c] = pd.to_numeric(act_df[c], errors="coerce")
            persons = persons.merge(act_df, on="delegate_id", how="left")

    for col in ("birth_year", "death_year"):
        if col not in persons.columns:
            persons[col] = pd.NA

    # extract geslachtsnaam
    fname_col = next((c for c in ("fullname", "full_name", "naam") if c in persons.columns), None)
    if fname_col:
        persons["geslachtsnaam"] = (
            persons[fname_col].astype(str).str.split(",", n=1).str[0].str.strip().str.lower()
        )
    else:
        persons["geslachtsnaam"] = pd.NA

    # Precompute name_mismatch once per delegate from the persons frame.
    # geslachtsnaam and pattern are both person-level attributes — no need to
    # recheck on every occurrence row after the merge.
    if "geslachtsnaam" in persons.columns and "pattern" in persons.columns:
        g_arr = persons["geslachtsnaam"].fillna("").to_numpy(dtype=str)
        p_arr = persons["pattern"].fillna("").str.lower().to_numpy(dtype=str)
        # Use nullable Boolean so the column survives a left-merge without
        # silently becoming object dtype (bool + NaN → object → mis-categorised).
        persons["name_mismatch"] = pd.array(
            np.char.find(p_arr, g_arr) < 0, dtype="boolean"
        )
    else:
        persons["name_mismatch"] = pd.array([False] * len(persons), dtype="boolean")

    # apply bulk remappings
    remap_dict: dict[str, str] = {
        str(r["from_id"]): str(r["to_id"])
        for r in (remappings or [])
        if r.get("from_id") and r.get("to_id")
    }
    if remap_dict and "delegate_id" in df_i.columns:
        _remap_mask = df_i["delegate_id"].astype(str).isin(remap_dict)
        _n_remapped_rows = int(_remap_mask.sum())
        df_i = df_i.copy()
        df_i.loc[_remap_mask, "delegate_id"] = (
            df_i.loc[_remap_mask, "delegate_id"].astype(str).map(remap_dict)
        )
    else:
        _n_remapped_rows = 0

    # filter placeholder occurrences (delegate_id == -1 or -20)
    if "delegate_id" in df_i.columns:
        _placeholder_mask = df_i["delegate_id"].astype(str).isin({"-1", "-20"})
        _n_placeholder_rows = int(_placeholder_mask.sum())
        df_i = df_i[~_placeholder_mask].copy()
    else:
        _n_placeholder_rows = 0

    if "delegate_id" in df_i.columns:
        df_i["delegate_id"] = df_i["delegate_id"].astype(str)
    if "delegate_id" in persons.columns:
        persons["delegate_id"] = persons["delegate_id"].astype(str)

    # Safety dedup: if abbrd had multiple rows per delegate the bio merges
    # above may have multiplied persons rows — collapse back to one per id.
    if "delegate_id" in persons.columns:
        persons = persons.drop_duplicates(subset=["delegate_id"])

    # Remove null / na delegate ids from both sides before merging.
    # astype(str) converts NaN → "nan" / "<NA>"; these form a cartesian
    # product in the merge (all null-id occurrences × all null-id persons).
    _null_ids = {"nan", "none", "<na>", "", "nat"}
    if "delegate_id" in persons.columns:
        persons = persons[~persons["delegate_id"].str.lower().isin(_null_ids)]
    if "delegate_id" in df_i.columns:
        df_i = df_i[~df_i["delegate_id"].str.lower().isin(_null_ids)]

    df = df_i.merge(persons, on="delegate_id", how="left", suffixes=("", "_p"))

    # Pattern validity marker for filtering and corrections.
    df["pattern_is_valid"] = True
    if "pattern" in df.columns:
        invalid_patterns = {"invalid", "<invalid>", "none", "<none>"}
        inv_mask = df["pattern"].astype(str).str.lower().isin(invalid_patterns)
        df.loc[inv_mask, "pattern_is_valid"] = False

    persisted = load_pattern_status()
    if "delegate_id" in df.columns and "pattern" in df.columns:
        def _pattern_key(series):
            did = str(series.get("delegate_id", ""))
            pat = str(series.get("pattern", ""))
            year = "" if pd.isna(series.get("j")) else str(int(series.get("j")))
            return f"{did}|{pat}|{year}"

        keys = df.apply(_pattern_key, axis=1)
        for idx, key in keys.items():
            if key in persisted:
                df.at[idx, "pattern_is_valid"] = persisted[key]

    if "j" not in df.columns and "date" in df.columns:
        df["j"] = pd.to_datetime(df["date"], errors="coerce").dt.year
    if "j" in df.columns:
        df["j"] = pd.to_numeric(df["j"], errors="coerce")
        by = pd.to_numeric(df["birth_year"], errors="coerce")
        df["age_at_event"] = df["j"] - by
    else:
        df["j"] = pd.NA
        df["age_at_event"] = pd.NA

    df = df.loc[:, ~df.columns.duplicated()].copy()

    # Convert repeated string columns to Categorical — encodes strings as
    # integer codes once so every subsequent groupby/nunique/value_counts uses
    # cheap int comparisons instead of string hashing.
    # Threshold: any object column whose unique count is < 50 % of total rows
    # (i.e. values repeat on average at least twice) is worth categorising.
    # Exclusions: boolean-valued columns (True/False +NaN) and columns whose
    # values are numeric-as-strings — both cause TypeError on sum/min/max.
    _n = len(df)
    if _n > 0:
        for _col in df.select_dtypes(include=["object", "string"]).columns:
            if df[_col].nunique() >= _n * 0.5:
                continue
            _sample = df[_col].dropna()
            if _sample.empty:
                continue
            # Skip if values look numeric (year strings, id numbers, …)
            if pd.to_numeric(_sample, errors="coerce").notna().mean() > 0.1:
                continue
            # Skip if values are boolean-like (True/False stored as Python objects)
            if set(_sample.unique()).issubset({True, False}):
                continue
            df[_col] = df[_col].astype("category")

    summary = _compute_delegate_summary(df, df_p, name_col)
    return df, _n_placeholder_rows, _n_remapped_rows, summary

=== _compute_delegate_summary code ===
def _compute_delegate_summary(
    df_merged: pd.DataFrame,
    df_p: pd.DataFrame,
    name_col: str,
) -> pd.DataFrame:
    """Build per-delegate aggregation from df_merged.

    Called inside build_merged (which is already cached) so the 600k-row
    DataFrame is never hashed a second time by a separate cached function.

    Issue columns added (sortable in the overview grid):
      n_alive_flags     — rows where age_at_event < MIN_AGE, > MAX_AGE, or j > death_year
      n_name_mismatches — rows where geslachtsnaam is not found in pattern
      max_gap_years     — largest consecutive year gap between appearances
    """
    if df_merged.empty:
        return pd.DataFrame()
    agg: dict = {"j": ["count", "min", "max"]}
    if "pattern" in df_merged.columns:
        agg["pattern"] = "nunique"
    summary = df_merged.groupby("delegate_id", observed=True).agg(agg).reset_index()
    summary.columns = ["_".join(c).strip("_") for c in summary.columns]
    summary = summary.rename(columns={
        "j_count": "n_occurrences",
        "j_min": "first_year",
        "j_max": "last_year",
        "pattern_nunique": "n_patterns",
    })

    # ---- alive flags -------------------------------------------------------
    if "age_at_event" in df_merged.columns:
        age = pd.to_numeric(df_merged["age_at_event"], errors="coerce").to_numpy()
        flag = (age < MIN_AGE) | (age > MAX_AGE)
        if "death_year" in df_merged.columns and "j" in df_merged.columns:
            j_n  = pd.to_numeric(df_merged["j"],          errors="coerce").to_numpy()
            dy_n = pd.to_numeric(df_merged["death_year"],  errors="coerce").to_numpy()
            flag = flag | (j_n > dy_n)
        alive_counts = (
            pd.Series(flag, index=df_merged.index, name="n_alive_flags")
            .groupby(df_merged["delegate_id"], observed=True).sum()
            .astype(int)
        )
        summary = summary.merge(alive_counts, on="delegate_id", how="left")

    # ---- name mismatches (pre-computed column on df_merged) ---------------
    if "name_mismatch" in df_merged.columns:
        mm_counts = (
            df_merged.groupby("delegate_id", observed=True)["name_mismatch"]
            .sum()
            .astype(int)
            .rename("n_name_mismatches")
        )
        summary = summary.merge(mm_counts, on="delegate_id", how="left")

    # ---- max consecutive year gap -----------------------------------------
    if "j" in df_merged.columns:
        gd = (
            pd.DataFrame({
                "delegate_id": df_merged["delegate_id"].to_numpy(),
                "j": pd.to_numeric(df_merged["j"], errors="coerce").to_numpy(),
            })
            .dropna(subset=["j"])
            .sort_values(["delegate_id", "j"])
        )
        gd["_diff"] = gd.groupby("delegate_id")["j"].diff()
        max_gaps = (
            gd.groupby("delegate_id")["_diff"]
            .max()
            .rename("max_gap_years")
            .astype("Int64")
        )
        summary = summary.merge(max_gaps, on="delegate_id", how="left")

    # Ensure delegates that appear in the persons file but have zero occurrences
    # still show up in the overview (with NaNs for counts).
    if "delegate_id" in df_p.columns:
        all_delegates = pd.DataFrame({"delegate_id": df_p["delegate_id"].astype(str).unique()})
        summary = all_delegates.merge(summary, on="delegate_id", how="left")

    # ---- name lookup & column ordering ------------------------------------
    if name_col in df_p.columns:
        summary = summary.copy()
        summary["delegate_id"] = summary["delegate_id"].astype(str)
        df_p_copy = df_p[["delegate_id", name_col]].copy()
        df_p_copy["delegate_id"] = df_p_copy["delegate_id"].astype(str)
        summary = summary.merge(
            df_p_copy.drop_duplicates(subset=["delegate_id"]),
            on="delegate_id", how="left",
        )
    issue_cols = [c for c in ("n_alive_flags", "n_name_mismatches", "max_gap_years")
                  if c in summary.columns]
    front = [c for c in (name_col, "delegate_id") if c in summary.columns]
    mid   = [c for c in summary.columns if c not in front and c not in issue_cols]
    return summary[front + mid + issue_cols].reset_index(drop=True)

persons shape: (1008, 14) occurrences shape: (430026, 19)
13613 in persons count: 1
duplicate delegate_ids in persons: 57
build_merged result: (420747, 37) placeholders 2161 remapped 84
summary shape: (951, 9)
13613 in summary: (1, 9)
duplicate delegate_id in summary: 0
recomputed summary shape: (951, 9)
13613 in recomputed summary: (1, 9)
duplicate delegate_id recomputed: 0

In [8]:
assert "13613" in summary["delegate_id"].astype(str).values
assert summary["delegate_id"].astype(str).duplicated().sum() == 0
assert df_merged["delegate_id"].dtype == object
assert summary.equals(summary2) or summary[["delegate_id","n_occurrences"]].set_index("delegate_id").equals(summary2[["delegate_id","n_occurrences"]].set_index("delegate_id"))

In [9]:
df_merged

,Kolom1,offset,end,class,pattern,oud id,delegate_id,delegate_name,delegate_score,d,...,resolutie_refs,minjaar,maxjaar,pattern_p,heerlijkheid,birth_year,death_year,name_mismatch,pattern_is_valid,age_at_event
0,427232,353,360,delegate,Jordens,None,236,"Jordens, Gerrit Dqavid",0.0,17,...,NaN,1795.0,NaN,Jordens;Martis den 17 Maart 1795 Het eerste ja...,NaN,NaN,NaN,False,True,NaN
1,427245,276,283,delegate,Jordens,None,236,"Jordens, Gerrit Dqavid",0.0,18,...,NaN,1795.0,NaN,Jordens;Martis den 17 Maart 1795 Het eerste ja...,NaN,NaN,NaN,False,True,NaN
2,427257,225,232,delegate,Jordens,None,236,"Jordens, Gerrit Dqavid",0.0,19,...,NaN,1795.0,NaN,Jordens;Martis den 17 Maart 1795 Het eerste ja...,NaN,NaN,NaN,False,True,NaN
3,427271,261,268,delegate,Jordens,None,236,"Jordens, Gerrit Dqavid",0.0,20,...,NaN,1795.0,NaN,Jordens;Martis den 17 Maart 1795 Het eerste ja...,NaN,NaN,NaN,False,True,NaN
4,427282,278,285,delegate,Jordens,None,236,"Jordens, Gerrit Dqavid",0.0,23,...,NaN,1795.0,NaN,Jordens;Martis den 17 Maart 1795 Het eerste ja...,NaN,NaN,NaN,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420742,287913,237,240,delegate,Can,None,21971,van Canter,0.0,6,...,NaN,1760.0,1760.0,van Canter;Van Canter;Can;Chan,NaN,NaN,NaN,False,True,NaN
420743,359725,505,508,delegate,Can,None,21971,van Canter,0.0,19,...,NaN,1760.0,1760.0,van Canter;Van Canter;Can;Chan,NaN,NaN,NaN,False,True,NaN
420744,359799,387,390,delegate,Can,None,21971,van Canter,0.0,23,...,NaN,1760.0,1760.0,van Canter;Van Canter;Can;Chan,NaN,NaN,NaN,False,True,NaN
420745,394980,434,437,delegate,Can,None,21971,van Canter,0.0,13,...,NaN,1760.0,1760.0,van Canter;Van Canter;Can;Chan,NaN,NaN,NaN,False,True,NaN
420746,396407,332,336,delegate,Chan,None,21971,van Canter,0.0,7,...,NaN,1760.0,1760.0,van Canter;Van Canter;Can;Chan,NaN,NaN,NaN,False,True,NaN

In [10]:
summary

,fullname,delegate_id,n_occurrences,first_year,last_year,n_patterns,n_alive_flags,n_name_mismatches,max_gap_years
0,"Abbink, Bernard Engelbert",18744,4.0,1787.0,1787.0,2.0,0.0,4.0,0
1,"Ablaing, Johan Daniël d'Giessenburg en Haulchi...",18379,4576.0,1726.0,1775.0,252.0,0.0,0.0,21
2,"Acquet, Hendrik Georgesz. d'",13591,141.0,1755.0,1758.0,3.0,0.0,0.0,1
3,"Alberda van Bloemersma en Bijma, Edzard Reint",17565,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
4,"Alberda van Resuma, Mello",<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
...,...,...,...,...,...,...,...,...,...
946,None,-1,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
947,None,-20,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
948,None,18451,5.0,1713.0,1721.0,5.0,0.0,5.0,4
949,"Piccardt, Jan",17544,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
950,"Berkhout, Pieter Jacob Teding van",13613,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [11]:
df_merged.shape

(420747, 37)

In [12]:
import importlib, utils
importlib.reload(utils)
utils.build_merged.clear()

from utils import build_merged, _compute_delegate_summary, load_data, source_mtimes, load_remappings

df_p, df_i, df_abbrd = load_data(source_mtimes())
remappings = load_remappings()

df_merged, n_placeholder, n_remapped, summary = build_merged(
    df_p, df_i, df_abbrd,
    extra_delegates=None,
    remappings=remappings,
    name_col="fullname"
)

summary2 = _compute_delegate_summary(df_merged, df_p, "fullname")

print("build_merged rows:", df_merged.shape[0], "cols:", df_merged.shape[1])
print("n_placeholder:", n_placeholder, "n_remapped:", n_remapped)
print("summary rows:", summary.shape[0], "cols:", summary.shape[1])
print("summary2 rows:", summary2.shape[0], "cols:", summary2.shape[1])
print("13613 in summary:", summary[summary["delegate_id"] == "13613"].shape)
print("13613 in summary2:", summary2[summary2["delegate_id"] == "13613"].shape)
print("dup delegate_id summary:", summary["delegate_id"].duplicated().sum())
print("dup delegate_id summary2:", summary2["delegate_id"].duplicated().sum())
print("merged delegate_id dtype:", df_merged["delegate_id"].dtype)
print("persons delegate_id dtype:", df_p["delegate_id"].dtype)

print("\n=== merged sample for 13613 ===")
print(df_merged[df_merged["delegate_id"] == "13613"].head(5).to_string(index=False))

print("\n=== summary for 13613 ===")
print(summary[summary["delegate_id"] == "13613"].to_string(index=False))

2026-03-24 16:29:09.758 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.759 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.759 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.761 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.761 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.762 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.762 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.762 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.763 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.763 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-24 16:29:09.847 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

build_merged rows: 420747 cols: 37
n_placeholder: 2161 n_remapped: 84
summary rows: 951 cols: 9
summary2 rows: 951 cols: 9
13613 in summary: (1, 9)
13613 in summary2: (1, 9)
dup delegate_id summary: 0
dup delegate_id summary2: 0
merged delegate_id dtype: object
persons delegate_id dtype: Int64

=== merged sample for 13613 ===
Empty DataFrame
Columns: [Kolom1, offset, end, class, pattern, oud id, delegate_id, delegate_name, delegate_score, d, m, j, lowerpattern, name, namens, status, opmerkingen, niettevinden, correcties, cons_id_str, fullname, voornaam, tussenvoegsel, geslachtsnaam, geboortejaar, overlijdensjaar, provincie, resolutie_refs, minjaar, maxjaar, pattern_p, heerlijkheid, birth_year, death_year, name_mismatch, pattern_is_valid, age_at_event]
Index: []

=== summary for 13613 ===
                         fullname delegate_id  n_occurrences  first_year  last_year  n_patterns  n_alive_flags  n_name_mismatches  max_gap_years
Berkhout, Pieter Jacob Teding van       13613            NaN         NaN        NaN         NaN            NaN                NaN           <NA>

In [13]:
summary

,fullname,delegate_id,n_occurrences,first_year,last_year,n_patterns,n_alive_flags,n_name_mismatches,max_gap_years
0,"Abbink, Bernard Engelbert",18744,4.0,1787.0,1787.0,2.0,0.0,4.0,0
1,"Ablaing, Johan Daniël d'Giessenburg en Haulchi...",18379,4576.0,1726.0,1775.0,252.0,0.0,0.0,21
2,"Acquet, Hendrik Georgesz. d'",13591,141.0,1755.0,1758.0,3.0,0.0,0.0,1
3,"Alberda van Bloemersma en Bijma, Edzard Reint",17565,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
4,"Alberda van Resuma, Mello",<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
...,...,...,...,...,...,...,...,...,...
946,None,-1,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
947,None,-20,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
948,None,18451,5.0,1713.0,1721.0,5.0,0.0,5.0,4
949,"Piccardt, Jan",17544,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
950,"Berkhout, Pieter Jacob Teding van",13613,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [14]:
summary[summary["delegate_id"] == "13613"]

,fullname,delegate_id,n_occurrences,first_year,last_year,n_patterns,n_alive_flags,n_name_mismatches,max_gap_years
950,"Berkhout, Pieter Jacob Teding van",13613,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [15]:
assert summary.loc[summary['delegate_id']=='13613', 'n_occurrences'].item() > 0
assert (summary['delegate_id'].astype(str).duplicated().sum() == 0)

AssertionError:

In [16]:
assert summary.loc[summary['delegate_id']=='13613', 'n_occurrences'].item() > 0
assert (summary['delegate_id'].astype(str).duplicated().sum() == 0)

AssertionError: